server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #过期时间

fdfs:
  so-timeout: 1501  #超时时间
  connect-timeout: 601  #连接超时时间
  thumb-image:  #上传原图和缩略图，可返回缩略图url给前端
    width: 60
    height: 60
  tracker-list:  #tracker地址
    - 192.168.10.130:22122


ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
